version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: test-postgress
    restart: unless-stopped
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test_dev_password
      POSTGRES_DB: test
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=und-u-ks-level1 --locale=C.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./seed_clients.data:/docker-entrypoint-initdb.d/seed_clients.data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
